 EXTRN SBDetect:Proc
 EXTRN SBWriteInfo:Proc
 EXTRN PlayTM3:Proc
 EXTRN StopTM3:Proc
 EXTRN LoadTM3:Proc

 EXTRN TM3SyncCount: DWord
 EXTRN SBVer: Word
 EXTRN Stereo: Byte
 EXTRN LoopIt: Byte
 EXTRN SamplingRate:Word

 EXTRN ADR: Word
 EXTRN IRQ: Byte
 EXTRN DMA: Byte

 EXTRN SampleP:DWord
 EXTRN CSampleP:DWord
 EXTRN PatternLine:Byte
 EXTRN Speed:Byte
 EXTRN GlobalVol:Byte

 EXTRN Channels:Byte
 EXTRN StartPattern:DWord
 EXTRN CPattern:Word
 EXTRN Songlen:Byte
 EXTRN Order:Byte
 EXTRN PatNum:Byte